services:
  python_demo:
    container_name: python-demo-server
    image: python-demo-server:${TAG}
    build:
      context: python-demo
      dockerfile: Dockerfile
    expose:
      - 8006
    ports:
      - 8006:8006
    networks:
      - webnet

  python_api:
    container_name: python-api-server
    image: python-api-server:${TAG}
    build:
      context: python-api
      dockerfile: Dockerfile
    expose:
      - 8007
    ports:
      - 8007:8007
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
