services:
  python-mongo-server:
    container_name: python-mongo-server
    image: mongo:4.0
    volumes:
      - /Users/lincenying/web/mongodb/data:/data/db
    ports:
      - 27017:27017
    networks:
      - webnet

  python-demo-server:
    container_name: python-demo-server
    image: python-demo-server:${TAG}
    build:
      context: python-demo
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mongodb://python-mongo-server:27017
    expose:
      - 8006
    depends_on:
      - python-mongo-server
    ports:
      - 8006:8006
    networks:
      - webnet

  python-api-server:
    container_name: python-api-server
    image: python-api-server:${TAG}
    build:
      context: python-api
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: mongodb://python-mongo-server:27017
    expose:
      - 8007
    depends_on:
      - python-mongo-server
    ports:
      - 8007:8007
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
